export interface User {
  id: string;
  name: string;
  username: string;
  email: string;
}
// Payload for creating — id is generated by backend, not sent by client
export type CreateUserInput = Omit<User, 'id'>;

// Payload for updating — all fields optional, id comes from URL param
export type UpdateUserInput = Partial<CreateUserInput>;